name: IaC
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  IaC:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Infrastructure as Code"
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
    env:
      TF_VAR_passwd: ${{ secrets.PASSWD }}
