name: IaC
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  IaC:
    runs-on: ubuntu-latest
    steps:
    - name: "Infrastructure as Code"
    env:
      TF_VAR_passwd: ${{ secrets.PASSWD }}
