name: IaC
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  IaC:
    name: "Infrastructure as Code"
    runs-on: ubuntu-latest
    env:
      TF_VAR_passwd: ${{ secrets.PASSWD }}
