name: Terraform Plan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  Terraform-Plan:
    runs-on: ubuntu-latest
    
    env:
        TF_VARS_passwd: ${{ secrets.PASSWD }}
